import { v4 as uuid } from 'uuid';
import type { Product } from '@/types';

export const products: Product[] = [
  {
    _id: uuid(),
    title: 'One Arranged Marriage',
    author: 'Chetan Bhagat',
    categoryName: 'contemporary-fiction',
    price: '147',
    prevPrice: '225',
    discount: '35',
    rating: '4.4',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/71fgd+WAkHL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Atomic habbits',
    author: 'James Clear',
    categoryName: 'self-help',
    price: '500',
    prevPrice: '799',
    discount: '36',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/51S7KOWir7L._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Attitude Is Everything',
    author: 'Jeff Keller',
    categoryName: 'self-help',
    price: '139',
    prevPrice: '199',
    discount: '30',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/710jnzKlDTL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Becoming',
    author: 'Michelle Obama',
    categoryName: 'biographies-autobiographies',
    price: '442',
    prevPrice: '699',
    discount: '37',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91EhnA7oXHL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Can Love Happen Twice',
    author: 'Ravinder Singh',
    categoryName: 'contemporary-fiction',
    price: '133',
    prevPrice: '199',
    discount: '33',
    rating: '4.3',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91xqVJ2ZkXL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Chanakya Neeti',
    author: 'Chanakya',
    categoryName: 'spirituality',
    price: '126',
    prevPrice: '175',
    discount: '28',
    rating: '4.4',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81uqBB0yjVL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Death',
    author: 'Sadhguru',
    categoryName: 'spirituality',
    price: '191',
    prevPrice: '299',
    discount: '36',
    rating: '4.7',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91co3ZyqsML._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Deep Work',
    author: 'Cal Newport',
    categoryName: 'self-help',
    price: '325',
    prevPrice: '399',
    discount: '19',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/814IUt6WOKL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Girl In Room 105',
    author: 'Chetan Bhagat',
    categoryName: 'contemporary-fiction',
    price: '114',
    prevPrice: '199',
    discount: '43',
    rating: '4.4',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81l9tZKRZLL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Half Girlfriend',
    author: 'Chetan Bhagat',
    categoryName: 'contemporary-fiction',
    price: '100',
    prevPrice: ' 250',
    discount: '60',
    rating: '4.2',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/712HEn9SNwL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Ikigai',
    author: 'Héctor García and Francesc Miralles',
    categoryName: 'self-help',
    price: '295',
    prevPrice: '255',
    discount: '46',
    rating: '4.6',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/81l3rZK4lnL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Karma',
    author: 'Sadhguru',
    categoryName: 'spirituality',
    price: '148',
    prevPrice: '299',
    discount: '51',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/9167i2ioFaS._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Leaders Eat Last',
    author: 'Simon Sinek',
    categoryName: 'self-help',
    price: '386',
    prevPrice: '599',
    discount: '36',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/71rMrK1DdZL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Power Of Letting Go',
    author: 'John Purkiss',
    categoryName: 'self-help',
    price: '590',
    prevPrice: '650',
    discount: '0',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/61bKDUjhloL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: "Life's Amazing Secrets",
    author: 'Gaur Gopal Das',
    categoryName: 'spirituality',
    price: '215',
    prevPrice: '225',
    discount: ' 4',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81N7FmJhbhL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'I Too Had A Love Story',
    author: 'Ravinder Singh',
    categoryName: 'contemporary-fiction',
    price: '191',
    prevPrice: '199',
    discount: ' 4',
    rating: '4.4',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81fxf8EaTgL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Meluha',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '302',
    prevPrice: '499',
    discount: '39',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/8181LdPn39L._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Nagas',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '245',
    prevPrice: '450',
    discount: '46',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91+4ShnL4TL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Power Of Now',
    author: 'Eckhart Tolle',
    categoryName: 'spirituality',
    price: '340',
    prevPrice: '499',
    discount: '32',
    rating: '4.5',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81rTrhtGDvL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Psychology Of Money',
    author: 'Morgan Housel',
    categoryName: 'self-help',
    price: '267',
    prevPrice: '399',
    discount: '33',
    rating: '4.6',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Ram',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '272',
    prevPrice: '450',
    discount: '40',
    rating: '4.4',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81um1SFs6QL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Ravaan',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '259',
    prevPrice: '499',
    discount: '48',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/812dmVf1V8S._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    categoryName: 'self-help',
    price: '243',
    prevPrice: '499',
    discount: '51',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Secrets',
    author: 'Rhonda Byrne',
    categoryName: 'self-help',
    price: '477',
    prevPrice: '799',
    discount: '40',
    rating: '4.6',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/81fdQIY6ykL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Sita',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '350',
    prevPrice: '299',
    discount: '12',
    rating: '4.5',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/61HK5Tm1QyL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The 5 AM Revolution',
    author: 'Dan Luca',
    categoryName: 'spirituality',
    price: '169',
    prevPrice: '295',
    discount: '43',
    rating: '4.3',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/611UKbv6bPL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    categoryName: 'spirituality',
    price: '229',
    prevPrice: '350',
    discount: '35',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Bhagavadgita',
    author: 'S. Radhakrishnan',
    categoryName: 'spirituality',
    price: '293',
    prevPrice: '499',
    discount: '41',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91DhR3OJboL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Power Of Intuition',
    author: 'Emma Lucy Knowles',
    categoryName: 'spirituality',
    price: '473',
    prevPrice: '599',
    discount: '21',
    rating: '4.5',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/71iJbC57J3L._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Subtle Art',
    author: 'Mark Manson',
    categoryName: 'self-help',
    price: '269',
    prevPrice: '499',
    discount: '46',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/814jC+rODgL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Think Like A Monk',
    author: 'Jay Shetty',
    categoryName: 'spirituality',
    price: '338',
    prevPrice: '499',
    discount: '32',
    rating: '4.6',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81s6DUyQCZL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Unfinished',
    author: 'Priyanka Chopra Jonas',
    categoryName: 'biographies-autobiographies',
    price: '352',
    prevPrice: '699',
    discount: '50',
    rating: '4.4',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/81tHdhbrGEL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Vayuputras',
    author: 'Amish Tripathi',
    categoryName: 'mythology',
    price: '403',
    prevPrice: '599',
    discount: '33',
    rating: '4.6',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91gLF02WsHL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'You Can Win',
    author: 'Shiv Khera',
    categoryName: 'self-help',
    price: '279',
    prevPrice: '399',
    discount: '30',
    rating: '3.8',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/81r9oQNPuNL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    categoryName: 'self-help',
    price: '100',
    prevPrice: '199',
    discount: '51',
    rating: '3.9',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image:
      'https://m.media-amazon.com/images/I/51qw-StAobL._AC_UY436_FMwebp_QL65_.jpg',
  },
  {
    _id: uuid(),
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham ',
    categoryName: 'self-help',
    price: '480',
    prevPrice: '799',
    discount: '40',
    rating: '4.5',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image:
      'https://m.media-amazon.com/images/I/91+t0Di07FL._AC_UY436_FMwebp_QL65_.jpg',
  },

  // Fyodor Dostoevsky
  {
    _id: uuid(),
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    categoryName: 'contemporary-fiction',
    price: '199',
    prevPrice: '395',
    discount: '50',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    categoryName: 'contemporary-fiction',
    price: '299',
    prevPrice: '599',
    discount: '50',
    rating: '4.8',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Notes from Underground',
    author: 'Fyodor Dostoevsky',
    categoryName: 'contemporary-fiction',
    price: '149',
    prevPrice: '250',
    discount: '40',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780679734529-L.jpg',
  },

  // Franz Kafka
  {
    _id: uuid(),
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    categoryName: 'contemporary-fiction',
    price: '99',
    prevPrice: '199',
    discount: '50',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780553213690-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Trial',
    author: 'Franz Kafka',
    categoryName: 'contemporary-fiction',
    price: '179',
    prevPrice: '350',
    discount: '49',
    rating: '4.4',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780805209990-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Castle',
    author: 'Franz Kafka',
    categoryName: 'contemporary-fiction',
    price: '189',
    prevPrice: '325',
    discount: '42',
    rating: '4.3',
    bestseller: false,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9780805211061-L.jpg',
  },

  // Fredrik Backman
  {
    _id: uuid(),
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    categoryName: 'contemporary-fiction',
    price: '239',
    prevPrice: '399',
    discount: '40',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781476738024-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Anxious People',
    author: 'Fredrik Backman',
    categoryName: 'contemporary-fiction',
    price: '274',
    prevPrice: '450',
    discount: '39',
    rating: '4.5',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781501160837-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Beartown',
    author: 'Fredrik Backman',
    categoryName: 'contemporary-fiction',
    price: '289',
    prevPrice: '499',
    discount: '42',
    rating: '4.4',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9781501160769-L.jpg',
  },

  // Khaled Hosseini
  {
    _id: uuid(),
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    categoryName: 'contemporary-fiction',
    price: '250',
    prevPrice: '399',
    discount: '37',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg',
  },
  {
    _id: uuid(),
    title: 'A Thousand Splendid Suns',
    author: 'Khaled Hosseini',
    categoryName: 'contemporary-fiction',
    price: '265',
    prevPrice: '450',
    discount: '41',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg',
  },
  {
    _id: uuid(),
    title: 'And the Mountains Echoed',
    author: 'Khaled Hosseini',
    categoryName: 'contemporary-fiction',
    price: '285',
    prevPrice: '499',
    discount: '43',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781594631764-L.jpg',
  },

  // Sally Rooney
  {
    _id: uuid(),
    title: 'Normal People',
    author: 'Sally Rooney',
    categoryName: 'contemporary-fiction',
    price: '299',
    prevPrice: '499',
    discount: '40',
    rating: '4.3',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Beautiful World, Where Are You',
    author: 'Sally Rooney',
    categoryName: 'contemporary-fiction',
    price: '329',
    prevPrice: '550',
    discount: '40',
    rating: '4.1',
    bestseller: false,
    newRelease: true,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9780374602604-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Conversations with Friends',
    author: 'Sally Rooney',
    categoryName: 'contemporary-fiction',
    price: '279',
    prevPrice: '450',
    discount: '38',
    rating: '4.0',
    bestseller: false,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9780451499066-L.jpg',
  },

  // Freida McFadden
  {
    _id: uuid(),
    title: 'The Housemaid',
    author: 'Freida McFadden',
    categoryName: 'contemporary-fiction',
    price: '249',
    prevPrice: '399',
    discount: '38',
    rating: '4.4',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9781538742570-L.jpg',
  },
  // Chitra Banerjee Divakaruni
  {
    _id: uuid(),
    title: 'The Palace of Illusions',
    author: 'Chitra Banerjee Divakaruni',
    categoryName: 'mythology',
    price: '239',
    prevPrice: '399',
    discount: '40',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9781400096206-L.jpg',
  },
  // Agatha Christie
  {
    _id: uuid(),
    title: 'Murder on the Orient Express',
    author: 'Agatha Christie',
    categoryName: 'contemporary-fiction',
    price: '179',
    prevPrice: '299',
    discount: '40',
    rating: '4.6',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780062693662-L.jpg',
  },
  {
    _id: uuid(),
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    categoryName: 'contemporary-fiction',
    price: '159',
    prevPrice: '275',
    discount: '42',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Murder of Roger Ackroyd',
    author: 'Agatha Christie',
    categoryName: 'contemporary-fiction',
    price: '169',
    prevPrice: '299',
    discount: '43',
    rating: '4.6',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780062073563-L.jpg',
  },

  // More fiction
  {
    _id: uuid(),
    title: '1984',
    author: 'George Orwell',
    categoryName: 'contemporary-fiction',
    price: '199',
    prevPrice: '350',
    discount: '43',
    rating: '4.7',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg',
  },
  {
    _id: uuid(),
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    categoryName: 'contemporary-fiction',
    price: '249',
    prevPrice: '399',
    discount: '38',
    rating: '4.8',
    bestseller: true,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    categoryName: 'contemporary-fiction',
    price: '139',
    prevPrice: '250',
    discount: '44',
    rating: '4.5',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg',
  },
  {
    _id: uuid(),
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    categoryName: 'contemporary-fiction',
    price: '319',
    prevPrice: '550',
    discount: '42',
    rating: '4.6',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    categoryName: 'contemporary-fiction',
    price: '219',
    prevPrice: '350',
    discount: '37',
    rating: '4.3',
    bestseller: false,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg',
  },
  {
    _id: uuid(),
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    categoryName: 'contemporary-fiction',
    price: '289',
    prevPrice: '499',
    discount: '42',
    rating: '4.4',
    bestseller: false,
    newRelease: false,
    expertPick: true,
    image: 'https://covers.openlibrary.org/b/isbn/9780375704024-L.jpg',
  },
  {
    _id: uuid(),
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    categoryName: 'contemporary-fiction',
    price: '229',
    prevPrice: '399',
    discount: '43',
    rating: '4.4',
    bestseller: true,
    newRelease: false,
    expertPick: false,
    image: 'https://covers.openlibrary.org/b/isbn/9780812979657-L.jpg',
  },
];
